<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Configurations>Debug;Release;NativeAot</Configurations>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Authors>tesuri</Authors>
    <Company>tesuri.org</Company>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

</Project>
