<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.*" />
    <PackageReference Include="MSTest.TestFramework" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tonono3\Tonono3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Tonono3\resources\config.yaml" Link="config.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
