<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
    <Version>1.2.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Constants.fs" />
    <Compile Include="EngineTypes.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="KanaConverter.fs" />
    <Compile Include="Dictionary.fs" />
    <Compile Include="CommandContext.fs" />
    <Compile Include="EngineComposition.fs" />
    <Compile Include="Engine.fs" />
    <Compile Include="Presentation.fs" />
    <Compile Include="Facade.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="tsr-di.Attribute" Version="1.0.3" />
  </ItemGroup>
</Project>
